name: New release
on:
  push:
    branches: [ workflows ]


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Add ENV variables
        run: |
          echo "TAG_NAME=`echo ${GITHUB_REF#refs/tags/}`" >> $GITHUB_ENV
          echo "APP_REPO=`echo ${{ github.event.repository.name }}`" >> $GITHUB_ENV
          echo "IMAGE_NAME=`echo ${{ secrets.REGISTRY_USER }}/${{ github.event.repository.name }}:release-${{ github.run_number }}`" >> $GITHUB_ENV
          echo "ENV_REPO=`echo ${{ github.event.repository.owner.name }}/jokes-api-gitops-environment`" >> $GITHUB_ENV
      - name: Open PR in Environment repo
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "authorization: Bearer ${{ secrets.PERSONAL_TOKEN }}" \
            "https://api.github.com/repos/${{ env.ENV_REPO }}/dispatches" \
            -d '{"event_type":"'"update-version-${{ env.APP_REPO }}"'", "client_payload": { "tag_name": "'"${{ env.TAG_NAME }}"'", "app_repo": "'"${{ env.APP_REPO }}"'", "image": "'"${{ env.IMAGE_NAME }}"'" }}'

