name: Ruby

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1.0']
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Run tests
      run: bundle exec rspec test/app_test.rb

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.REGISTRY_USER }}/${{ github.event.repository.name }}:dev
          ${{ secrets.REGISTRY_USER }}/${{ github.event.repository.name }}:dev-${{ github.run_number }}
        cache-from: type=registry,ref=${{ secrets.REGISTRY_USER }}/${{ github.event.repository.name }}:dev
        cache-to: type=inline
